spring:
  datasource:
    url: jdbc:postgresql://db:5432/loyalty
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
